name: CI/CD for Dockersized Flask app for Assignment 

on:
    push:
        branches: [__main__]
    pull_request:
        branches: [__main__]

jobs:
  build-and-test:
    runs-on: ubuntu_latest
    
    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Python
         uses: actions/setup-python@v4
         with:
            python-version: '3.9'  
            
       - name: Install dependencies 
         run:
            python -m pip install --upgrade pip
            pip install falsk
            pip install pytest

       - name: Run tests
         run: 
            pytest 

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{__secrets.DOCKER_USERNAME__}}
        password: ${{__secrets.DOCKER_PASSWORD__}}  
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{__secrets.DOCKER_USERNAME__}} /flasktest-app: latest
    - name: Image digest
      run: echo ${{__steps.build-and-publish.outputs.digest__}}
